= FreeRADIUS using Google Authenticator

== Build base FreeRADIUS images

This images is based on `fedora:35`

.buildBaseFreeRadius.sh
[source, bash]
----
podman build -f Dockerfile.basefreeradius -t basefreeradius .
----

== Build FreeRADIUS images with modifications

.buildFreeRadius.sh

[source, bash]
----
podman build -f Dockerfile -t freeradius .
----

== Start the container

.runFreeRadius.sh

[source, bash]
----
podman run -it --rm --privileged --log-level=debug \
  --name freeradius1 \
  --hostname freeradius1.dk \
  -p 1812:1812/udp \
  -p 1813:1813/udp \
  -p 18120:18120/udp freeradius
----

== Run bash in the container

.bashFreeRadius.sh

[source, bash]
----
podman exec -it freeradius1 /bin/bash
----

== Generate .google_authenticator file

Use `bashFreeRadius.sh` to log into the server a do

[source, bash]
----
su micbn google_authenticator
----

follow the steps in `google_authenticator`

[source, bash]
----
cat /home/micbn/.google_authenticator
----

add content of `/home/micbn/.google_authenticator` into this project `.google_authenticator`

CAUTION: No not share you `.google_authenticator` file ;o)

== Update clients

Add new client to the end of the file `clients.conf`


== Test the setup

`radtest <user> <password+google authenticator token> <host> <port> <RADIUS secret key>`

.Request
[source, bash]
----
radtest micbn micbnpassword4321177250 localhost 18120 testing1234
----

.Response
[source]
----
Sent Access-Request Id 21 from 0.0.0.0:45421 to 127.0.0.1:1812 length 91
        User-Name = "micbn"
        User-Password = "micbnpassword4321177250"
        NAS-IP-Address = 192.168.0.118
        NAS-Port = 18120
        Message-Authenticator = 0x00
        Cleartext-Password = "micbnpassword4321177250"
Received Access-Accept Id 21 from 127.0.0.1:1812 to 127.0.0.1:45421 length 20
----


== Links

- https://freeradius.org/[FreeRADIUS]
- https://networkjutsu.com/freeradius-google-authenticator/[Adding Two-Factor Authentication to FreeRADIUS]
- https://networkjutsu.com/ssh-google-authenticator/[Securing SSH with Google Authenticator]
- https://networkjutsu.com/freeradius-docker/[Migrated FreeRADIUS with Google Authenticator to a Docker container]
- https://github.com/google/google-authenticator-libpam[Google Authenticator PAM module]

- http://tinyradius.sourceforge.net/[TinyRadius: Java Radius library]